akrherz/iem

cgi-bin/request/gis/watchwarn.py

This should fix the issue w/the filename for state searches for issue #47

Vtec state fix

---

data/wms/q2.map

Reuses the legend config from the mrms mapfile

Add legend for WMS to q2 mapfile

---

htdocs/plotting/auto/scripts/__init__.py
htdocs/plotting/auto/scripts100/p183.py
htdocs/plotting/auto/scripts100/p186.py
htdocs/plotting/auto/scripts200/p206.py
scripts/current/today_gust.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=206

add autoplot for daily analyses from asos/awos

---

scripts/yieldfx/yieldfx_workflow.py

fix KeyError with yieldfx workflow

---

htdocs/json/vtec_events.py
htdocs/vtec/index.php
htdocs/vtec/vtec_app.js
htdocs/vtec/vtec_static.css

https://mesonet.agron.iastate.edu/vtec/
closes #153

improve VTEC browser

---

htdocs/nws/index.php
htdocs/nws/wpc_national_hilo/index.php

https://mesonet.agron.iastate.edu/nws/wpc_national_hilo/

add WPC national hi/lo app listing

---

cgi-bin/request/mos.py
htdocs/mos/dl.php
htdocs/mos/fe.phtml
htdocs/plotting/auto/scripts/p37.py

https://mesonet.agron.iastate.edu/mos/fe.phtml

forklift MOS download backend to python based

---

htdocs/plotting/auto/scripts/p37.py

correct NBE/NBS ~daily hi/lo plot

---

htdocs/plotting/auto/scripts100/p186.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=186

add conus option to USDM change

---

scripts/RUN_40_AFTER.sh
scripts/climodat/hrrr_solarrad.py
scripts/dl/download_hrrr_rad.py
scripts/dl/download_hrrr_tsoil.py

use more exact 15min HRRR ave radiation

---

htdocs/plotting/auto/scripts/__init__.py
htdocs/plotting/auto/scripts200/p243.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=243

add autoplot for top 10 VTEC dates

---

scripts/iemre/daily_analysis.py
scripts/iemre/hourly_analysis.py

fix more IEMRE things

---

htdocs/plotting/auto/scripts/p26.py
htdocs/projects/iembot/mastodon/index.py
scripts/climodat/compute_climate.py
scripts/ingestors/scan/scan_ingest.py
scripts/month/obs_precip.py
scripts/month/obs_precip_coop.py
scripts/qc/check_awos_online.py
scripts/qc/check_isusm_online.py

fix: database update whackamole

---

htdocs/plotting/auto/scripts100/p119.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=119

feat: first all low percentile dates table

---

htdocs/plotting/auto/scripts/p90.py
htdocs/search.py
scripts/climodat/check_database.py
scripts/dbutil/set_county.py
scripts/dbutil/set_wfo.py
scripts/hads/raw2obs.py
scripts/iemre/daily_analysis.py
scripts/iemre/hourly_analysis.py
scripts/ingestors/asos_1minute/parse_ncdc_asos1minute.py
scripts/ingestors/flux_ingest.py
scripts/ingestors/madis/extract_hfmetar.py
scripts/ingestors/rwis/process_soil.py
scripts/ingestors/soilm_ingest.py
scripts/isusm/agg_1minute.py
scripts/smos/ingest_smos.py

mnt: address more psycopg 3 issues

---

htdocs/nws/coop-cnts.php

https://mesonet.agron.iastate.edu/nws/coop-cnts.php

feat: add COOP counts by WFO per day

---

htdocs/plotting/auto/scripts/p56.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=56

warning climatology putzing

---

cgi-bin/request/gis/pireps.py
htdocs/request/gis/pireps.php

https://mesonet.agron.iastate.edu/request/gis/pireps.php

feat: add ARTCC filter to PIREP download

---

htdocs/rainfall/obhour-json.php
htdocs/rainfall/obhour-static.js
htdocs/rainfall/obhour.phtml

https://mesonet.agron.iastate.edu/rainfall/obhour.phtml

feat: add more intervals to hourly precip accum

---

htdocs/plotting/auto/scripts/p42.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=42

feat: add at-or-below option to consec hours app

---

htdocs/plotting/auto/scripts100/p148.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=148

feat: add MLK option to holiday autoplot

---

htdocs/plotting/auto/scripts/p52.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=52

feat: add bells+whistles to VTEC WFO Gantt chart

---

htdocs/topics/pests/index.php
htdocs/topics/pests/main.js

https://mesonet.agron.iastate.edu/topics/pests/

fix: UI issues with pests GDD tool

---

htdocs/plotting/auto/scripts/__init__.py
htdocs/plotting/auto/scripts200/p200.py
htdocs/plotting/auto/scripts200/p248.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=248

feat: autoplot showing SPC/WPC outlooks by st/wfo

---

htdocs/iemre/index.phtml
htdocs/plotting/auto/scripts/p86.py
scripts/RUN_0Z.sh
scripts/RUN_10_AFTER.sh
scripts/RUN_MIDNIGHT.sh
scripts/RUN_NOON.sh
scripts/dbutil/add_iem_data_entry.py
scripts/dbutil/add_summary_entries.py
scripts/dbutil/clean_afos.py
scripts/dbutil/clean_mos.py
scripts/dbutil/clean_telemetry.py
scripts/dbutil/clean_unknown_hads.py
scripts/iemre/daily_analysis.py
scripts/iemre/db_to_netcdf.py
scripts/iemre/hourly_analysis.py
scripts/iemre/init_daily.py
scripts/iemre/init_dailyc.py

Continued thrashing working on dailyerosion/dep#212

IEMRE Updates

---

scripts/RUN_0Z.sh
scripts/RUN_NOON.sh
scripts/RUN_STAGE4.sh
scripts/iemre/precip_ingest.py

fix: script calls related to stage4 ingest

---

cgi-bin/request/gis/lsr.py
htdocs/request/gis/lsrs.phtml
include/forms.php

https://mesonet.agron.iastate.edu/request/gis/lsrs.phtml

feat: add LSR type filter to download

---

htdocs/plotting/auto/scripts100/p113.py
scripts/util/list_stale_autoplots.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=113 closes #679

feat: enhance daily climo plotting

---

htdocs/plotting/auto/scripts/__init__.py
htdocs/plotting/auto/scripts/p54.py
htdocs/plotting/auto/scripts200/p250.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=250

feat: add autoplot comp two station hourly vars

---

cgi-bin/request/taf.py
htdocs/plotting/auto/scripts200/p219.py
htdocs/request/taf.php

https://mesonet.agron.iastate.edu/cgi-bin/request/taf.py?help

doc and fix TAF usage per akrherz/pyIEM#453

---

cgi-bin/request/scp.py
htdocs/api/index.php

https://mesonet.agron.iastate.edu/cgi-bin/request/scp.py?help

feat: add bulk download of ASOS SCP

---

cgi-bin/request/tempwind_aloft.py
htdocs/request/tempwind_aloft.php

https://mesonet.agron.iastate.edu/cgi-bin/request/tempwind_aloft.py?help

doc and use pydantic for tempwind_aloft service

---

cgi-bin/request/gis/watchwarn.py

https://mesonet.agron.iastate.edu/cgi-bin/request/gis/watchwarn.py?help

feat: use pydantic for watchwarn backend

---

cgi-bin/request/purpleair.py
htdocs/other/index.phtml

https://mesonet.agron.iastate.edu/other/#purpleair

feat: add download of purpleair data

---

htdocs/plotting/auto/scripts/p44.py
htdocs/plotting/auto/scripts/p73.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=73

feat: allow user defined period

---

pylib/iemweb/autoplot/scripts/p25.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=25

feat: add single station option

---

cgi-bin/request/hourlyprecip.py
htdocs/request/asos/hourlyprecip.phtml

https://mesonet.agron.iastate.edu/cgi-bin/request/hourlyprecip.py?help

doc: asos hourly precip service

---

.github/workflows/etchosts.txt
pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts200/p254.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=254

feat: add autoplot of NEXRAD latencies

---

pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts/p52.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=52

feat: add UGC option for Gantt Chart

---

cgi-bin/request/gis/sigmets.py
htdocs/request/gis/awc_sigmets.phtml

https://mesonet.agron.iastate.edu/cgi-bin/request/gis/sigmets.py?help

feat: update sigmet backend for csv,excel support

---

.github/workflows/build.yml
pylib/iemweb/autoplot/index.py
pylib/iemweb/autoplot/scripts/p17.py
pylib/iemweb/autoplot/scripts/p28.py
pylib/iemweb/autoplot/scripts100/p113.py
pylib/iemweb/json/nwstext.py
tests/iemweb/autoplot/urllist.txt

Should be another coverage win with yet another quirk found with the test data included in the iem-database repo.

mnt: increase coverage

---

pylib/iemweb/autoplot/scripts200/p211.py
tests/iemweb/autoplot/urllist.txt

https://mesonet.agron.iastate.edu/plotting/auto/?q=211

fix: correct asos1minute wind plot

---

pylib/iemweb/json/climodat_dd.py
pylib/iemweb/json/spcoutlook.py
pylib/iemweb/request/asos1min.py
pylib/iemweb/request/gis/watchwarn.py
tests/iemweb/test_doc_urls.py

hoping for a coverage win here.

mnt: sundry updates per review

---

htdocs/request/coop/fe.phtml
pylib/iemweb/autoplot/scripts/p32.py
pylib/iemweb/request/coop.py
scripts/RUN_2AM.sh
scripts/climodat/power_extract.py

feat: build out NASA POWER Solar Rad extraction

---

pylib/iemweb/autoplot/scripts/p24.py
tests/iemweb/autoplot/urllist.txt

https://mesonet.agron.iastate.edu/plotting/auto/?q=24

feat: add SDD option to climate/state ranks

---

scripts/hrrr/hrrr_ref2raster.py

seems like wgrib2 has a bug, sigh
fixes #903

fix: use rasterio to reproject HRRR

---

htdocs/api/index.php
htdocs/projects/iao/analog_download.php
pylib/iemweb/request/talltowers.py

https://mesonet.agron.iastate.edu/cgi-bin/request/talltowers.py?help

✨ Improve talltowers download backend

---

htdocs/kml/sbw_interval.php
htdocs/request/gis/watchwarn.phtml

https://mesonet.agron.iastate.edu/request/gis/watchwarn.phtml

🐛 Correct KML download of VTEC emergencies

---

pylib/iemweb/autoplot/scripts200/p230.py
pylib/iemweb/geojson/agclimate.py
pylib/iemweb/geojson/winter_roads.py
pylib/iemweb/precip/catAZOS.py
pylib/iemweb/request/hourlyprecip.py
pylib/iemweb/search.py
scripts/RUN_0Z.sh
scripts/RUN_10_AFTER.sh
scripts/RUN_MIDNIGHT.sh
scripts/climodat/ks_monthly.py
scripts/climodat/merra_solarrad.py
scripts/current/ifc_today_total.py
scripts/qc/check_afos.py
scripts/qc/check_n0q.py
tests/iemweb/autoplot/urllist.txt
tests/iemweb/urls422.txt

Hoping for a coverage win here.

📝 Sundry updates per review

---

pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts200/p232.py
tests/iemweb/autoplot/urllist.txt

https://mesonet.agron.iastate.edu/plotting/auto/?q=232

✨ Add fire weather plotting option

---

pylib/iemweb/geojson/lsr.py
tests/iemweb/urls422.txt

https://mesonet.agron.iastate.edu/geojson/lsr.py?help

✨ Add crude spatial bounds filter to LSR service

---

cgi-bin/request/gis/misc.py
htdocs/request/gis/misc.phtml
htdocs/request/gis/outlooks.phtml
htdocs/request/gis/spc_mcd.phtml
htdocs/request/gis/spc_watch.phtml
htdocs/request/gis/watchwarn.phtml
htdocs/request/gis/wpc_mpd.phtml
pylib/iemweb/request/gis/misc.py
tests/iemweb/urls.txt

https://mesonet.agron.iastate.edu/request/gis/misc.phtml

✨ Add download of NWS misc polygons

---

cgi-bin/request/hml.py
htdocs/api/index.php
htdocs/nws/index.php
htdocs/request/hml.php
pylib/iemweb/autoplot/scripts100/p160.py
pylib/iemweb/autoplot/scripts200/p224.py
pylib/iemweb/request/hml.py

https://mesonet.agron.iastate.edu/request/hml.php
refs #277

✨ Add HML Download Portal

---

config/mesonet.inc
htdocs/vtec/index.php
htdocs/vtec/vtec_app.js
pylib/iemweb/json/vtec_event.py
pylib/iemweb/json/vtec_events_bypoint.py
pylib/iemweb/vtec/f.py

Will fix any javascript errors deepsource comes back with...

VTEC browser updates

---

htdocs/agclimate/hist/daily.php
pylib/iemweb/request/isusm.py
tests/iemweb/urls.txt

https://mesonet.agron.iastate.edu/agclimate/hist/daily.php

✨ Add daily chill hours to ISUSM daily download

---

htdocs/sites/networks.php
pylib/iemweb/geojson/network.py
tests/iemweb/urls.txt

https://mesonet.agron.iastate.edu/sites/networks.php?network=HAS_HML
refs #1010

✨ Add HAS_HML table to networks

---

pylib/iemweb/autoplot/scripts/p84.py
scripts/prism/init_daily.py
scripts/prism/init_prism_dailyc.py

🐛 Fix PRISM grid navigation

---

pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts/p53.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=53

✨ Add more hourly variables to frequency autoplot

---

pylib/iemweb/autoplot/scripts100/p148.py
tests/iemweb/autoplot/urllist.txt

https://mesonet.agron.iastate.edu/plotting/auto/?q=148

✨ Add snow depth to holiday autoplot

---

pylib/iemweb/autoplot/scripts/p90.py
pylib/iemweb/autoplot/scripts100/p124.py
pylib/iemweb/autoplot/scripts100/p131.py
pylib/iemweb/autoplot/scripts100/p135.py
pylib/iemweb/autoplot/scripts100/p146.py
pylib/iemweb/autoplot/scripts100/p154.py
pylib/iemweb/autoplot/scripts100/p155.py
pylib/iemweb/autoplot/scripts100/p156.py
pylib/iemweb/autoplot/scripts100/p157.py
pylib/iemweb/autoplot/scripts100/p161.py
pylib/iemweb/autoplot/scripts100/p162.py

Side goal, see what updated pyiem iemapp does.

📝 Address some datetime lint

---

pylib/iemweb/autoplot/scripts200/p256.py
pylib/iemweb/request/asos.py

https://mesonet.agron.iastate.edu/plotting/auto/?q=256
* attempt to delinate ASOS from AWOS
* only consider utc hour modulo 6 snow reports

✨ RTP generator improvements

---

htdocs/sites/taf.js
htdocs/sites/taf.php
pylib/iemweb/afos/retrieve.py

https://mesonet.agron.iastate.edu/sites/taf.php?station=DSM&network=IA_ASOS

✨ Add Aviation AFD, Recent METARS

---

pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts200/p259.py
tests/iemweb/autoplot/urllist.txt

✨ Add NWS UGC geometry autoplot diagnostic

---

htdocs/api/index.php
htdocs/geojson/station_neighbors.py
htdocs/sites/neighbors.php
include/sites.php
pylib/iemweb/geojson/station_neighbors.py
tests/iemweb/urls422.txt

https://mesonet.agron.iastate.edu/geojson/station_neighbors.py?help

✨ Add station neighbors GeoJSON adhoc service

---

cgi-bin/request/gis/spc_mcd.py
htdocs/json/mcd_bysize.py
htdocs/json/spcmcd.py
htdocs/nws/mcd_top10.phtml
htdocs/nws/spc_outlook_search/index.phtml
htdocs/nws/spc_outlook_search/search.js
htdocs/request/gis/spc_mcd.phtml
pylib/iemweb/json/mcd_bysize.py
pylib/iemweb/json/spcmcd.py
pylib/iemweb/request/gis/spc_mcd.py

plus additional linting
refs akrherz/pyIEM#1042

✨ Support MCD Intensity tags

---

pylib/iemweb/autoplot/__init__.py
pylib/iemweb/autoplot/scripts200/p243.py
tests/iemweb/autoplot/urllist.txt

https://mesonet.agron.iastate.edu/plotting/auto/?q=243

✨ Add multi-day option to VTEC top10 event counts

---

htdocs/DCP/plot.js
htdocs/archive/raob/list.js
htdocs/info/datasets.php
htdocs/rainfall/obhour-static.js

Can we get a green PR for St Patrick's Day?

📝 Address some deepsource lint

---

htdocs/COOP/index.phtml
htdocs/agclimate/soilt.php
htdocs/agweather/index.php
htdocs/current/index.phtml
htdocs/current/radar.phtml
htdocs/iemre/index.phtml
htdocs/index.phtml
htdocs/mos/index.php
htdocs/nws/index.php
htdocs/roads/index.phtml
htdocs/smos/index.php
htdocs/timemachine/index.php
htdocs/timemachine/static.js
htdocs/timemachine/style.css
scripts/cache/download_cpc.sh
scripts/cache/nws_wawa_archive.py

https://mesonet.agron.iastate.edu/timemachine/

🎨 Improve IEM Timemachine

---

htdocs/nws/spc_outlook_search/index.phtml
htdocs/nws/spc_outlook_search/search.css
htdocs/nws/spc_outlook_search/search.js

https://mesonet.agron.iastate.edu/nws/spc_outlook_search/

✨ Add support for D4-8 on SPC Outlook Search

---

pylib/iemweb/autoplot/scripts200/p207.py
tests/iemweb/autoplot/urllist.txt

Updated test data in iem-database should help here.

💚 Increase coverage

---

pylib/iemweb/autoplot/scripts/p84.py
pylib/iemweb/iemre/daily.py
pylib/iemweb/iemre/multiday.py
pylib/iemweb/json/prism.py
scripts/iemre/prism_adjust_stage4.py
scripts/prism/ingest_prism.py
scripts/prism/init_daily.py
scripts/prism/init_prism_dailyc.py

✨ Switch to PRISM 800m Product

---

config/mesonet.inc
htdocs/cow/maplsr.phtml
htdocs/index.phtml
htdocs/lsr/old.phtml

https://mesonet.agron.iastate.edu/lsr/

🚚 Make room for new LSR App

---

htdocs/COOP/7am-app.js
htdocs/COOP/7am.css
htdocs/COOP/7am.php
pylib/iemweb/geojson/seven_am.py

https://mesonet.agron.iastate.edu/COOP/7am.php

🐛 Fix bugs with COOP 7am App

---

pylib/iemweb/autoplot/index.py
tests/iemweb/urls422.txt

Small commit to get things started and see if codecov is going to play ball.

🐛 Prevent bad autoplot dates

---

pylib/iemweb/autoplot/scripts200/p249.py
scripts/RUN_10_AFTER.sh
scripts/RUN_40_AFTER.sh
scripts/iemre/use_icon.py

✨ Add DWD ICON Dataflow into IEMRE non-CONUS

---

htdocs/nws/list_tags.css
htdocs/nws/list_tags.php
pylib/iemweb/json/ibw_tags.py

https://mesonet.agron.iastate.edu/nws/list_tags.php

✨ Add filter by state option to IBW Tags Listing
